// CodeGear C++Builder
// Copyright (c) 1995, 2024 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'System.Messaging.pas' rev: 36.00 (Windows)

#ifndef System_MessagingHPP
#define System_MessagingHPP

#pragma delphiheader begin
#pragma option push
#if defined(__BORLANDC__) && !defined(__clang__)
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#endif
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>
#include <System.SysUtils.hpp>
#include <System.Generics.Collections.hpp>
#include <System.Generics.Defaults.hpp>
#include <System.Types.hpp>

//-- user supplied -----------------------------------------------------------

namespace System
{
namespace Messaging
{
//-- forward type declarations -----------------------------------------------
class DELPHICLASS TMessageBase;
template<typename T> class DELPHICLASS TMessage__1;
template<typename T> class DELPHICLASS TObjectMessage__1;
__interface DELPHIINTERFACE TMessageListener;
typedef System::DelphiInterface<TMessageListener> _di_TMessageListener;
class DELPHICLASS TMessageManager;
//-- type declarations -------------------------------------------------------
#ifndef _WIN64
#pragma pack(push,4)
#endif /* not _WIN64 */
class PASCALIMPLEMENTATION TMessageBase : public System::TObject
{
	typedef System::TObject inherited;
	
public:
	/* TObject.Create */ inline __fastcall TMessageBase() : System::TObject() { }
	/* TObject.Destroy */ inline __fastcall virtual ~TMessageBase() { }
	
};

#ifndef _WIN64
#pragma pack(pop)
#endif /* not _WIN64 */

#ifndef _WIN64
#pragma pack(push,4)
#endif /* not _WIN64 */
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION TMessage__1 : public TMessageBase
{
	typedef TMessageBase inherited;
	
protected:
	T FValue;
	
public:
	__fastcall TMessage__1(const T AValue);
	__fastcall virtual ~TMessage__1();
	__property T Value = {read=FValue};
};

#ifndef _WIN64
#pragma pack(pop)
#endif /* not _WIN64 */

#ifndef _WIN64
#pragma pack(push,4)
#endif /* not _WIN64 */
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename T> class PASCALIMPLEMENTATION TObjectMessage__1 : public TMessage__1<T>
{
	typedef TMessage__1<T> inherited;
	
protected:
	bool FOwnsObject;
	
public:
	__fastcall TObjectMessage__1(const T AValue, bool AOwnsObject);
	__fastcall virtual ~TObjectMessage__1();
};

#ifndef _WIN64
#pragma pack(pop)
#endif /* not _WIN64 */

__interface TMessageListener  : public System::IInterface 
{
	virtual void __fastcall Invoke(System::TObject* const Sender, TMessageBase* const M) = 0 ;
};

typedef void __fastcall (__closure *TMessageListenerMethod)(System::TObject* const Sender, TMessageBase* const M);

typedef __int64 TMessageSubscriptionId;

#ifndef _WIN64
typedef System::TMetaClass* TMessageManagerClass;
#else /* _WIN64 */
_DECLARE_METACLASS(System::TMetaClass, TMessageManagerClass);
#endif /* _WIN64 */

class PASCALIMPLEMENTATION TMessageManager : public System::TObject
{
	typedef System::TObject inherited;
	
	
protected:
	class DELPHICLASS TListenerData;
	class PASCALIMPLEMENTATION TListenerData : public System::TObject
	{
		typedef System::TObject inherited;
		
	public:
		TMessageSubscriptionId Id;
		_di_TMessageListener Listener;
		TMessageListenerMethod ListenerMethod;
		bool MarkedAsRemoved;
		__fastcall TListenerData(const TMessageSubscriptionId AId, const TMessageListenerMethod AListenerMethod)/* overload */;
		__fastcall TListenerData(const TMessageSubscriptionId AId, const _di_TMessageListener AListener)/* overload */;
		void __fastcall MarkAsRemoved();
	public:
		/* TObject.Destroy */ inline __fastcall virtual ~TListenerData() { }
		
	};
	
	
	class DELPHICLASS TListenerList;
#ifndef _WIN64
	#pragma pack(push,4)
#endif /* not _WIN64 */
	class PASCALIMPLEMENTATION TListenerList : public System::TObject
	{
		typedef System::TObject inherited;
		
	private:
		System::Generics::Collections::TObjectList__1<TMessageManager::TListenerData*>* FListeners;
		System::Generics::Collections::TDictionary__2<__int64,TMessageManager::TListenerData*>* FIndicies1;
		System::Generics::Collections::TDictionary__2<_di_TMessageListener,TMessageManager::TListenerData*>* FIndicies2;
		System::Generics::Collections::TDictionary__2<TMessageListenerMethod,TMessageManager::TListenerData*>* FIndicies3;
		int FProcessing;
		int FRemoveCount;
		int FRemoveThreshold;
		void __fastcall IterateAndSend(System::TObject* const Sender, TMessageBase* const AMessage);
		void __fastcall RemoveDelayed();
		void __fastcall MarkAsRemoved(TMessageManager::TListenerData* const AListener);
		void __fastcall Unsubscribe(TMessageManager::TListenerData* const AListener)/* overload */;
		void __fastcall RecalculateRemoveThreshold();
		
	public:
		__fastcall TListenerList();
		__fastcall virtual ~TListenerList();
		TMessageSubscriptionId __fastcall Subscribe(const TMessageSubscriptionId AId, const _di_TMessageListener AListener)/* overload */;
		TMessageSubscriptionId __fastcall Subscribe(const TMessageSubscriptionId AId, const TMessageListenerMethod AListenerMethod)/* overload */;
		void __fastcall SendMessage(System::TObject* const Sender, TMessageBase* const AMessage);
		void __fastcall Unsubscribe(const TMessageSubscriptionId AId)/* overload */;
		void __fastcall Unsubscribe(const _di_TMessageListener AListener)/* overload */;
		void __fastcall Unsubscribe(const TMessageListenerMethod AListenerMethod)/* overload */;
	};
	
#ifndef _WIN64
	#pragma pack(pop)
#endif /* not _WIN64 */
	
	typedef System::Generics::Collections::TObjectDictionary__2<System::TClass,TListenerList*> TListenerRegistry;
	
private:
	TMessageSubscriptionId FLastId;
	void __fastcall RegisterMessageClass(const System::TClass AMessageClass, TListenerList* &AListeners);
	static TMessageManager* FDefaultManager;
	static TMessageManagerClass FDefaultManagerClass;
	static TMessageManager* __fastcall GetDefaultManager();
	
protected:
	TListenerRegistry* FListeners;
	
public:
	__fastcall virtual TMessageManager();
	__fastcall virtual ~TMessageManager();
	
private:
	// __classmethod void __fastcall UnInitialize@();
	
public:
	virtual TMessageSubscriptionId __fastcall SubscribeToMessage(const System::TClass AMessageClass, const _di_TMessageListener AListener)/* overload */;
	virtual TMessageSubscriptionId __fastcall SubscribeToMessage(const System::TClass AMessageClass, const TMessageListenerMethod AListenerMethod)/* overload */;
	virtual void __fastcall Unsubscribe(const System::TClass AMessageClass, TMessageSubscriptionId Id, bool Immediate = false)/* overload */;
	virtual void __fastcall Unsubscribe(const System::TClass AMessageClass, const _di_TMessageListener AListener, bool Immediate = false)/* overload */;
	virtual void __fastcall Unsubscribe(const System::TClass AMessageClass, const TMessageListenerMethod AListenerMethod, bool Immediate = false)/* overload */;
	void __fastcall SendMessage(System::TObject* const Sender, TMessageBase* AMessage)/* overload */;
	virtual void __fastcall SendMessage(System::TObject* const Sender, TMessageBase* AMessage, bool ADispose)/* overload */;
	/* static */ __property TMessageManager* DefaultManager = {read=GetDefaultManager};
	/* static */ __property TMessageManagerClass DefaultManagerClass = {read=FDefaultManagerClass, write=FDefaultManagerClass};
	
private:
	// __classmethod void __fastcall Create@();
};


//-- var, const, procedure ---------------------------------------------------
}	/* namespace Messaging */
}	/* namespace System */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_SYSTEM_MESSAGING)
using namespace System::Messaging;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_SYSTEM)
using namespace System;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// System_MessagingHPP
